### ISSUE TITLE
`require 'rmagick'` tripped me up

### ISSUE THREAD

**Issue by eeeps** [nhoizey/jekyll-cloudinary#11]
The first time I tried to run Jekyll with this plugin, I got the following error:

```
LoadError: cannot load such file -- RMagick
  /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-cloudinary-1.2.14/lib/jekyll/cloudinary.rb:6:in `require'
```

I don’t know how Jekyll plugins are supposed to work, but I don’t see 'rmagick' listed in the plugin’s Gemfile?

After I `gem instal 'rmagick'`’d , everything ran smoothly.

**Comment by nhoizey** [comment]
You're right, the dependency is missing in the plugin spec
