### ISSUE TITLE
Specify crop settings? Will adding a 'crop' parameter to _config.yml work?

### ISSUE THREAD

**Issue by kry8vmedia** [nhoizey/jekyll-cloudinary#23]

**Comment by nhoizey** [comment]
Do you want to apply the same crop to:
- all images -> global setting
- every image with the same preset -> preset setting
- single images -> additional syntax in Liquid tag

**Comment by kry8vmedia** [comment]
I would like to add it as a preset setting. I think that would be most flexible for me

**Comment by aarongustafson** [comment]
I would love to see support for more of the transformation tools too. I think presets are a good place to start.

**Comment by nhoizey** [comment]
@kry8vmedia @aarongustafson I will try to take time soon to look how I can do this!

**Comment by aarongustafson** [comment]
I've got it pretty much working. Pull request coming tomorrow.

**Comment by nhoizey** [comment]
@aarongustafson awesome, thanks!

**Comment by aarongustafson** [comment]
INCOMING!

**Comment by aarongustafson** [comment]
You should be able to use crop in your presets now: https://github.com/nhoizey/jekyll-cloudinary/blob/master/lib/jekyll/cloudinary.rb#L26

**Comment by nhoizey** [comment]
@aarongustafson do you plan to make a PR with a few additions about this in the README? ;-)

**Comment by aarongustafson** [comment]
Can you add an issue and assign me? I may be able to tackle it on the plane
next week.

**Comment by nhoizey** [comment]
@aarongustafson I created the issue, but I can't assign it to you until you accept my invitation to be a collaborator on the project… ;-)

#27
