### ISSUE TITLE
Remove imagemagick dependency?

### ISSUE THREAD

**Issue by aarongustafson** [nhoizey/jekyll-cloudinary#25]
I've been running into some issues installing a project using this gem on both Windows and Mac and it doesn't seem like rmagick is being used for much more than verifying image dimensions. What do you think about looking at some alternatives that are a little bit more lightweight and less problematic from an install perspective?

**Comment by nhoizey** [comment]
It would be great indeed to remove this dependency, if possible.

**Comment by aarongustafson** [comment]
How would you feel about moving to [FastImage](https://github.com/sdsykes/fastimage)? It has zero additional dependencies and works with both URLs and local paths. It’s what the AMP image plugin uses and seems to work really well. I’m happy to kick off a branch to make the switch.

**Comment by nhoizey** [comment]
FastImage looks great indeed!

I'll be happy to merge a PR for this. ;-)

**Comment by aarongustafson** [comment]
That was pretty easy. Let me know how this works.

**Comment by eeeps** [comment]
There's probably a good reason, but I'm curious — why verify them locally, rather than just trusting [Cloudinary’s admin API](http://cloudinary.com/documentation/admin_api#details_of_a_single_resource)?

(just tested and it does work for `image/fetch` resources that have been previously requested)

**Comment by aarongustafson** [comment]
I am pretty sure the local verification code pre-existed my work on the plugin. It is currently used for FastImage to get the dimensions.

**Comment by nhoizey** [comment]
@eeeps local width/height verification let us generate the site without any Internet connection, a situation I am pretty often facing. Also, the admin API would mean the image has first to be uploaded to (or fetched by) Cloudinary, before generating the site.

I'm always trying to ease the life of the users… ;-)

**Comment by eeeps** [comment]
Makes sense. I knew there were good reasons! Thanks!

**Comment by nhoizey** [comment]
@eeeps you're welcome!

**Comment by nhoizey** [comment]
@aarongustafson I had to deal with local images with `image_path` instead of `image_url`: https://github.com/nhoizey/jekyll-cloudinary/commit/d00d1f5a0793ae69b1662fe63ceda83fdf213ca1#diff-7a8c866eef21f94d129ea1c2eb1d55aeR226

Do you use only remote images?

**Comment by aarongustafson** [comment]
@nhoizey Depends on the project. One I started using this plugin for is a mix.

**Comment by nhoizey** [comment]
@aarongustafson so it means your image files where already uploaded to the server, I guess.

Thanks again for these valuable additions!

**Comment by aarongustafson** [comment]
Or exist on another domain :-)

My pleasure! Thanks for making the plugin!
