### ISSUE TITLE
Add configuration to switch off the logic for localhost development

### ISSUE THREAD

**Issue by borisschapira** [nhoizey/jekyll-cloudinary#32]
```
cloudinary:
  mock: true #default: false
```

With this parameter to `true`, the use of Cloudinary is disabled, as well as the creation of `srcset` and `sizes`. A normal image tag is generated.

This would make it easier to consult pages containing images that are not yet available on the Web.

Translated with www.DeepL.com/Translator

**Comment by nhoizey** [comment]
Looks like a duplicate of #20

**Comment by borisschapira** [comment]
Yep
