### ISSUE TITLE
pass variable file name into module

### ISSUE THREAD

**Issue by DBHare** [nhoizey/jekyll-cloudinary#40]
I'm trying to pass a variable file name into the module and the build keeps failing.

`   {% for image in site.static_files %}
    {% if image.path contains 'img/photos' %}
    {% assign passingname = '/img/photos/' | append: image.basename | append: image.extname %}
    <div class="container-fluid">
            <div class="row no-gutter">
                <div class="col-lg-4 col-sm-6">
                    <a href="{{ image.path }}" class="portfolio-box lightbox-image" title="{{ image.basename | replace: '-, ' ' }}" >
                            {% cloudinary passingname  %}
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-name" style="text-transform:capitalize">
                                    {{ image.basename | replace: "-", " " }}
                                </  div>
                            </div>
                        </div>
                    </a>
                </div> 
        {% endif %}
        {% endfor %}
`
I've also tried
` {% cloudinary /img/photos/{{image.basename}}{{image.extname}} %} `
and
` {% cloudinary /img/photos/[image.basename][image.extname] %} `

but in both of those cases, the module just created a url with the variable names instead of the variable's contents. 

Am I just doing the liquid syntax incorrectly or is this not doable with the gem?

Thanks!

**Comment by nhoizey** [comment]
I don't think it's currently possible to use variables.

I'll try to find if there's a way to do that, thanks for asking.

**Comment by Marcosaurios** [comment]
It's possible to pass variable with a string, instead of the path string directly? Thanks and very good job!

**Comment by nhoizey** [comment]
I think recent documentation update answers this:
https://github.com/nhoizey/jekyll-cloudinary#liquid-tag-values
