### ISSUE TITLE
Support default upload folder

### ISSUE THREAD

**Issue by DirtyF** [nhoizey/jekyll-cloudinary#57]
Yo can use a single Cloudinary account on multiple sites, in that case you can use a different folder per site.

Could you add a setting for people to be able to point to a (sub)folder by default, e.g:

`folder: blog`

The tag would automatically fetch images stored in that folder only.

Thanks for considering that support.

**Comment by nhoizey** [comment]
This plugin "only" prefixes images full URLs with Cloudinary commands, so you can already use one single Cloudinary account with as many websites you want (I do it).

Also, there is no "automated fetch" involved, so images that are fetched are only the ones on visited pages that have Cloudinary bases URLs.

If you have an image at URL `https://example.com/blog/image.jpg` and you use the Liquid tag to add it to a Markdown content: `{% cloudinary /blog/image.jpg %}`, the page will contain an image which URL will be (for example) `http://res.cloudinary.com/<your_cloud_name>/image/fetch/c_limit,w_<resize_width>,q_auto,f_auto/https://example.com/blog/image.jpg`.

If there is another image at URL `https://example.com/about/logo.jpg` but you never use it in Markdown pages with the Liquid tag, it will never be fetched by Cloudinary.

Do you still think it would be useful adding a new feature, or is there more some misunderstanding coming from lack of documentation?
