### ISSUE TITLE
Dont’t wrap `alt` text in `<p>`

### ISSUE THREAD

**Issue by eeeps** [nhoizey/jekyll-cloudinary#8]
On my [test page](), the following tag:

```
{% cloudinary /assets/test.png alt="beautiful!" %}
```

produced an `img` with this `alt` attribute:

```
alt="<p>beautiful!</p> "
```

I can’t find it stated definitively anywhere, but markup doesn't belong in `alt`. e.g., all of the examples [in the W3C’s official guidance](https://dev.w3.org/html5/alt-techniques) are raw text.

**Comment by nhoizey** [comment]
You're right, it a bug, only the caption should run Markdownify
