### ISSUE TITLE
Spaces between transformation parameters?

### ISSUE THREAD

**Issue by eeeps** [nhoizey/jekyll-cloudinary#9]
On my [test page](http://jekyll-cloudinary.ericportis.com/testing/jekyll-cloudinary/2016/07/28/testing-cloudinary-integration.html), the URLs in `srcset` include spaces between the transform parameters, like this:

```
srcset="https://res.cloudinary.com/eric-cloudinary/image/fetch/c_scale, w_320, q_auto, f_auto/http://jekyll-cloudinary.ericportis.com/assets/test.png 320w, https://res.cloudinary.com/eric-cloudinary/image/fetch/c_scale, w_540, q_auto, f_auto/http://jekyll-cloudinary.ericportis.com/assets/test.png 540w, https://res.cloudinary.com/eric-cloudinary/image/fetch/c_scale, w_760, q_auto, f_auto/http://jekyll-cloudinary.ericportis.com/assets/test.png 760w, https://res.cloudinary.com/eric-cloudinary/image/fetch/c_scale, w_980, q_auto, f_auto/http://jekyll-cloudinary.ericportis.com/assets/test.png 980w, https://res.cloudinary.com/eric-cloudinary/image/fetch/c_scale, w_1200, q_auto, f_auto/http://jekyll-cloudinary.ericportis.com/assets/test.png 1200w"
```

I'm pretty surprised that the comma-spaces in the middle of the URLs don't trip up the `srcset` parser... or Cloudinary! Anyways, they shouldn't be there.

**Comment by nhoizey** [comment]
I don't have spaces in the URL that are in the HTML source, but I do see spaces in the devtools showing more the DOM than the actual HTML source.

I suppose devtools add spaces to ease reading…

**Comment by eeeps** [comment]
Yes, it appears that this is devtools trying to make `srcset`s easier to read. I'll try to submit a Chrome bug soonish.

**Comment by nhoizey** [comment]
@eeeps there's the same issue in Safari 9.1.2 at least
